# Generated by Django 3.0.6 on 2021-01-31 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quetion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('que_text', models.CharField(max_length=300)),
                ('que_text_raz', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='VeloMarsh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marsh_image', models.FileField(upload_to='images/')),
                ('marsh_text', models.CharField(max_length=300)),
            ],
        ),
    ]
